spring:
  data:
    mongodb:
      uri : mongodb://host.docker.internal:27023/Task
      database : Task

#spring:
#  data:
#    mongodb:
#      uri : mongodb+srv://Aprajput:Akshay9599@cluster0.sh2toj7.mongodb.net/Task
#      database : Task